"""init_db

Revision ID: c7c5a613d45f
Revises: 
Create Date: 2025-07-20 13:44:23.933765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c5a613d45f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('team_name', sa.String(length=80), nullable=True),
    sa.Column('department_name', sa.String(length=80), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modification_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=True)
    op.create_index(op.f('ix_account_user_name'), 'account', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_name'), table_name='account')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
